### ISSUE TITLE
Working multithreaded listeners

### ISSUE THREAD

**Issue by bfrog** [tailhook/rotor-http#1]
Multiple listener threads in action with the hello example, quite nice!

https://github.com/bfrog/rotor-http-hello

**Comment by tailhook** [comment]
Nice. Coincidentally I've done the same thing last night to do some micro-benchmarks. Pushed just now to "examples" folder. It looks similar to your example except the number of threads can be changed by the environment variable.

Anyway, thanks for giving a try!
