### ISSUE TITLE
Client Example

### ISSUE THREAD

**Issue by KodrAus** [tailhook/rotor-http#13]
Hi! Just wondering if there's any plans for a client sample for Rotor HTTP.

**Comment by tailhook** [comment]
It's not an example is missing, but the whole client implementation. It's cooking in [client](https://github.com/tailhook/rotor-http/tree/client) branch. Hopefully it will be ready soon. There is [an example](https://github.com/tailhook/rotor-stream/blob/master/examples/fetch.rs) in rotor-stream, which does "very tiny subset" of HTTP, if you just want to look how client code works in rotor.

**Comment by KodrAus** [comment]
No problem, thanks :)

**Comment by tailhook** [comment]
@KodrAus it's not fully implemented yet, but simple case works: https://github.com/tailhook/rotor-http/blob/master/examples/client.rs

**Comment by KodrAus** [comment]
@tailhook Ah awesome, thanks for that! I'll have a play with it. It looks like it should be pretty easy to build either a callback or promise-like API on top of this.

**Comment by tailhook** [comment]
@KodrAus let me know, if something emerged. You can also make a pull request to the [ecosystem page](http://rotor.readthedocs.org/en/latest/ecosystem.html)
