### ISSUE TITLE
How to test rotor-http?

### ISSUE THREAD

**Issue by pyfisch** [tailhook/rotor-http#23]
I want to write some tests to check how rotor-http handles various requests and responses.

**Comment by pyfisch** [comment]
One example of a not working request: `curl --header "Transfer-Encoding: chunked" -d @textfile.txt "http://127.0.0.1:3000/" -v` I send this request to the hello_world_server example.

**Comment by tailhook** [comment]
I don't have too much experience in writing tests. Probably feeding data to state machine should be good enough for the start.

I've just put a method `scope.now()`. Which allows to write time-related tests easier, but it's not very easy to create scope object yet.

I'm going to create a special crate with mock objects and certain fuzzy tests out of the box. But can't give concrete timeframe yet.

Regarding chunked encoding, I'm not sure I'll find some time during vacation. So it may take a time to the end of next week for me too debug the issue.

**Comment by briansmith** [comment]
Check out https://github.com/benoitc/gunicorn/tree/master/tests/requests, which might help. Some people who work on Python HTTP stuff seem quite interested in trying to build a data-driven test suite (i.e. the inputs and expected outputs are specified in a JSON file, and the test suite just loads these JSON files, interprets them, and makes sure the expected outputs match the actual outputs). @frewsxcv knows those people and may be able to connect you to them.

**Comment by tailhook** [comment]
Sounds good. But also note, that we use httparse for all the heavy-lifting of header parsing.

This means in rotor http we will probably need to test length determination, chunk coalescing, and similar things, rather than invalid bytes in headers.

But a suit of tests which could be shared across the implementations sounds promising anyway.

**Comment by pyfisch** [comment]
For the client http://httpbin.org could be used to test a wide range of requests and responses.

**Comment by tailhook** [comment]
Okay. I've added few tests for server-size implementation (https://github.com/tailhook/rotor-http/blob/master/src/server/parser.rs#L755) they are far from being comprehensive but already catched some bugs. @pyfisch, could you take a look?

**Comment by tailhook** [comment]
Okay. We have now all needed mocks for unittesting the rotor-http, and some tests. I feel this could be closed.

If anybody can come with more specific proposal about data-driven tests. Feel free to open another issue for that.
