### ISSUE TITLE
413 Payload Too Large

### ISSUE THREAD

**Issue by nokaa** [tailhook/rotor-http#24]
I've been playing with rotor-http recently, and I wanted to see if I could get file uploads working. I've been running into the problem where rotor-http returns a 413 for some uploads. When I attempted to use a 33KB textfile, a 413 was given.

Interestingly, a 6MB binary file did not give a 413. Instead, nothing happened. The server did not crash and no messages were printed.

I have made my work available [here](https://github.com/nokaa/rotor_test) if you would like to test this. 

I'm mostly wondering if this is expected behavior, or if this is just a stop gap until someone works on this part of rotor-http.

```
rustc -V
rustc 1.8.0-nightly (57c357d89 2016-02-16)
```

**Comment by tailhook** [comment]
You return `RecvMode::Buffered(1024)` from request handler. This means you accept requests with the body up to `1024` bytes. You should either make the number of bytes higher, if you're okay with loading everything into the memory, or use `RecvMode::Progressive` in that case you will receive multiple chunks (and the size in `Progressive` is just a hint).

I'm not sure why 6Mb file behaves this way, however. I'm on vacation now, will look into this later.

**Comment by nokaa** [comment]
Ah, I should have read the documentation better. Thank you, after increasing the number of bytes everything worked properly.

If there is anything I can do to help let me know.

**Comment by tailhook** [comment]
Well, we may have a guide/tutorial a little bit later. (Like when API is not in flux anymore)
