### ISSUE TITLE
State between requests?

### ISSUE THREAD

**Issue by pyfisch** [tailhook/rotor-http#25]
The methods `Server::request_received(self, data: &[u8], response: &mut Response,
        scope: &mut Scope<Self::Context>)` and `Server::request_end(self, response: &mut Response,  scope: &mut Scope<Self::Context>) -> Option<Self>` currently return an `Option<Self>`. This allows the server to keep state between requests but also adds a lot of complexity to the code.  All code I am aware of returns `None`. In which cases is it desirable to keep state between the requests from the client on the server except keep-alive?

**Comment by tailhook** [comment]
This functionality is not for sharing state between requests (I'm not sure it's possible with current implementation).

This is implemented so you can wait for some asynchronous event after a request is fully read, but before you have done with the response. I.e. you return state machine in `repsonse_end`, and then use a `Notifier` somewhere. And when notifier gets "wakeup()" you can use `&mut Response` object to start/finish the response.

**Comment by pyfisch** [comment]
Thanks for the explanation.

**Comment by 3Hren** [comment]
> This is implemented so you can wait for some asynchronous event after a request is fully read, but before you have done with the response. I.e. you return state machine in repsonse_end, and then use a Notifier somewhere. And when notifier gets "wakeup()" you can use &mut Response object to start/finish the response.

Can you show a minimal example of such deferred handler? I've been struggling for days looking for asynchronous HTTP servers to implement (almost) zero-copy proxy with the following simple scheme:

HTTP request -> read + write into something TCP -> async wait... -> read from something TCP -> write into HTTP response.

**Comment by tailhook** [comment]
@3Hren, I think the example is in basic-http-server

Here is the "pause" line: https://github.com/brson/basic-http-server/blob/master/src/main.rs#L313
following is the `wakeup` function.

Is this what you are looking for?

**Comment by 3Hren** [comment]
I think it is. Will look at the repository you've linked more precisely, thanks!
