### ISSUE TITLE
assertion failed server/parser.rs:223

### ISSUE THREAD

**Issue by nokaa** [tailhook/rotor-http#40]
I received this error earlier: 
```
thread '<main>' panicked at 'assertion failed: response.is_complete()', /home/nokaa/.multirust/toolchains/nightly/cargo/git/checkouts/rotor-http-aa821d917006c86c/master/src/server/parser.rs:223
```
At the time I was just sending data to a client, and I have not been able to replicate the error.

**Comment by pyfisch** [comment]
The relevant assertion can be found in [the parser](https://github.com/tailhook/rotor-http/blob/306544f7eb46cf3690d5696f56f362463c0b763e/src/server/parser.rs#L223). After the request body is received a response should be sent. If the user does not send a complete response this assertion fails. This means either rotor-http's state machine is wrong at some point or your code does not send under some circumstances a complete response. Is your code public so I can take a look?

**Comment by tailhook** [comment]
I second what @pyfisch said. And regardless of whether this specific problem is a problem with rotor-http or user code. We will have such issues with user code anyway.

So the question is if we can do better at this? Allow sending broken request is bad, and an assertion is probably a good way to discover this early on during development.

On the other hand, returning `None` from any handler in case you can't do anything better (like can't fetch next portion of the data in the middle of a request), is just so tempting.

**Comment by tailhook** [comment]
If it wasn't clear I mean, we could:

1. Fill response generation with some debug messages (so with RUST_LOG=debug you will get some mesages preceeding panic).
2. Print exact state the request is currently in, before panicking
3. Emit error log message instead of panic

(I'm pretty skeptical about (3) because this may delay when user will find out if there is something wrong with their code)

**Comment by nokaa** [comment]
@pyfisch The application code is [here](https://github.com/nokaa/lambda_chan/blob/master/src/routes.rs#L53). The function called for sending data is [here](https://github.com/nokaa/rotor-http-utils/blob/master/src/util.rs#L137).

**Comment by tailhook** [comment]
@nokaa at least in cases `Board(_)` and `Thread(_)` nothing is sent. And this is the case for assertion. You should send `501 Not Implemented` page or 404 error page instead of doing nothing in that cases until they are implemented.

**Comment by tailhook** [comment]
@nokaa  Is this solved?

**Comment by nokaa** [comment]
It seems like it. I haven't run into this since. My apologoies for the late response.
