### ISSUE TITLE
Persistent Connections

### ISSUE THREAD

**Issue by KodrAus** [tailhook/rotor-http#44]
Is it possible to write persistent HTTP connections with `rotor_http`? I'm still pretty new to the library so am not sure how that would play with the state functions on the `Client`. Could it just be a case of passing an already open socket to the `Requester` object?

**Comment by tailhook** [comment]
Sure:
1. Here is the example how to [create a connection](https://github.com/tailhook/rotor-cantal/blob/master/src/connection.rs#L23) 
2. [The code to create a request](https://github.com/tailhook/rotor-cantal/blob/master/src/generator.rs#L22), which we call on a [timeout](https://github.com/tailhook/rotor-cantal/blob/master/src/generator.rs#L75) (sending requests in a time intervals) and [wakeup](https://github.com/tailhook/rotor-cantal/blob/master/src/generator.rs#L64) (sending request now)

**Comment by KodrAus** [comment]
Ah great, thanks! I'll dig through your implementation
